title = input("enter your Title: ")
full_Name = input("enter your Fullname: ")
phone_Number = input("enter your Phone Number: ")
food_request = input("enter your food: ")
num = input("enter the number of portions: ")
print("hello! " + title  + full_Name + "," + " you just ordered " + food_request)

title = input (" enter your title: "  )
first_Name = input ( " enter your Firstname : "  )
surname = input  ( " enter your Surname  : "  )
phone_Number = input  ( " enter your Correct Phone Number: " )
food_request = input  ( " enter your food_request: " )
num = input (" num: ")
print("hello" + title +  first_Name + surname  + "! " +  "," + "you ordered " + food_request + ( num ))

title = input("enter your title: ")
first_Name = input("enter your Firstname: ")
sur_Name = input("enter your Surname: ")
phone_Number =input("enter your Correct Phone Number: ")
food_request = input("enter your food_request: ")
num = input("enter a number: ")

print("hello " + title + first_Name + surname  + phone_Number +"! you ordered "  + food_request + ( num := " enter the number of portions: "))

title = input("enter your title")
first_Name = input("enter your Name: ")
sur_Name = input("enter your Surname:")
phone_Number =input("enter your Correct Phone Number: ")
food_request = input("enter your food_request: ")
num = input("enter a number: ")
print("hello " +  first_Name + phone_Number + "! you ordered " + food_request + ( num := " enter a number of portions: "))

title = input("enter your title")
first_Name = input("enter your Name: ")
sur_Name = input("enter your Surname: ")
phone_Number =input("enter your Correct Phone Number: ")
food_request = input("enter your food_request: ")
num = input("enter a number: ")

print("hello " +  first_Name + phone_Number + "! you ordered " + food_request + ( num := " enter the  number of portions: "))

